// Catálogo canónico de productos a monitorear (193 productos).
// Incluye los 82 originales del frontend de demostración más una ampliación
// de referencias populares para que el MVP real tenga cobertura útil desde
// el día uno. Sin precios — los precios reales los llena el actualizador
// diario a partir de aquí.

export const CATALOG = [
  p("leche-gloria-entera-1l", "Leche Gloria Entera", "Gloria", "Lácteos", "1 L", 1, "L", ["Leche Gloria Entera 1L", "leche entera gloria"]),
  p("leche-gloria-light-1l", "Leche Gloria Light", "Gloria", "Lácteos", "1 L", 1, "L", ["Leche Gloria Light 1L"]),
  p("leche-gloria-deslactosada-1l", "Leche Gloria Sin Lactosa", "Gloria", "Lácteos", "1 L", 1, "L", ["Leche Gloria Deslactosada", "leche sin lactosa gloria"]),
  p("leche-gloria-evaporada-400g", "Leche Gloria Evaporada", "Gloria", "Lácteos", "Tarro 400 g", 0.4, "kg", ["Leche Gloria Evaporada Tarro"]),
  p("pack-leche-gloria-1l-x6", "Pack Leche Gloria Entera", "Gloria", "Lácteos", "Pack 6 x 1 L", 6, "L", ["Leche Gloria Entera pack 6"]),
  p("leche-laive-entera-1l", "Leche Laive Entera", "Laive", "Lácteos", "1 L", 1, "L", ["Leche Laive Entera 1L"]),
  p("yogurt-gloria-fresa-1l", "Yogurt Gloria Fresa", "Gloria", "Lácteos", "1 L", 1, "unidad", ["Yogurt Gloria Fresa 1L"]),
  p("yogurt-griego-gloria-150g", "Yogurt Griego Gloria", "Gloria", "Lácteos", "150 g", 1, "unidad", ["Yogurt Griego Gloria"]),
  p("pack-yogurt-griego-gloria-4x150g", "Pack Yogurt Griego Gloria", "Gloria", "Lácteos", "Pack 4 x 150 g", 4, "unidad", ["Yogurt Griego Gloria pack 4"]),
  p("yogurt-griego-gloria-light-150g", "Yogurt Griego Gloria Light", "Gloria", "Lácteos", "150 g", 1, "unidad", ["Yogurt Griego Gloria Light"]),
  p("leche-ideal-entera-1l", "Leche Ideal Entera", "Ideal", "Lácteos", "1 L", 1, "L", ["Leche Ideal Entera 1L"]),
  p("leche-bella-holandesa-1l", "Leche Bella Holandesa Entera", "Bella Holandesa", "Lácteos", "1 L", 1, "L", ["Leche Bella Holandesa"]),
  p("manjar-blanco-gloria-320g", "Manjar Blanco Gloria", "Gloria", "Lácteos", "320 g", 0.32, "kg", ["Manjarblanco Gloria"]),
  p("mantequilla-gloria-200g", "Mantequilla Gloria con Sal", "Gloria", "Lácteos", "200 g", 0.2, "kg", ["Mantequilla Gloria"]),
  p("mantequilla-laive-200g", "Mantequilla Laive", "Laive", "Lácteos", "200 g", 0.2, "kg", ["Mantequilla Laive"]),
  p("queso-fresco-paisano-400g", "Queso Fresco Paisano", "Laive", "Lácteos", "400 g", 0.4, "kg", ["Queso Fresco Paisano"]),
  p("queso-edam-bonle-250g", "Queso Edam Bonlé", "Bonlé", "Lácteos", "250 g", 0.25, "kg", ["Queso Edam Bonlé"]),
  p("queso-mozzarella-bonle-250g", "Queso Mozzarella Bonlé", "Bonlé", "Lácteos", "250 g", 0.25, "kg", ["Queso Mozzarella Bonlé"]),
  p("yogurt-laive-fresa-1l", "Yogurt Laive Fresa", "Laive", "Lácteos", "1 L", 1, "unidad", ["Yogurt Laive Fresa"]),
  p("crema-leche-gloria-200ml", "Crema de Leche Gloria", "Gloria", "Lácteos", "200 ml", 0.2, "L", ["Crema de Leche Gloria"]),
  p("leche-condensada-gloria-397g", "Leche Condensada Gloria", "Gloria", "Lácteos", "Tarro 397 g", 0.397, "kg", ["Leche Condensada Gloria tarro"]),
  p("coca-cola-zero-1.5l", "Coca-Cola Zero", "Coca-Cola", "Bebidas", "1.5 L", 1.5, "L", ["Coca Cola Zero 1.5L", "gaseosa coca cola zero"]),
  p("coca-cola-zero-500ml", "Coca-Cola Zero", "Coca-Cola", "Bebidas", "500 ml", 500, "ml", ["Coca Cola Zero 500ml"]),
  p("coca-cola-original-1.5l", "Coca-Cola Original", "Coca-Cola", "Bebidas", "1.5 L", 1.5, "L", ["Coca Cola 1.5L"]),
  p("inca-kola-1.5l", "Inca Kola", "Inca Kola", "Bebidas", "1.5 L", 1.5, "L", ["Inca Kola 1.5L"]),
  p("agua-san-luis-sin-gas-1l", "Agua San Luis Sin Gas", "San Luis", "Bebidas", "Botella 1 L", 1, "L", ["Agua San Luis sin gas botella 1L"]),
  p("sprite-1.5l", "Sprite", "Sprite", "Bebidas", "1.5 L", 1.5, "L", ["Sprite 1.5L"]),
  p("fanta-1.5l", "Fanta", "Fanta", "Bebidas", "1.5 L", 1.5, "L", ["Fanta 1.5L"]),
  p("pepsi-1.5l", "Pepsi", "Pepsi", "Bebidas", "1.5 L", 1.5, "L", ["Pepsi 1.5L"]),
  p("guarana-backus-1.5l", "Guaraná Backus", "Backus", "Bebidas", "1.5 L", 1.5, "L", ["Guaraná Backus"]),
  p("kola-real-1.5l", "Kola Real", "Kola Real", "Bebidas", "1.5 L", 1.5, "L", ["Kola Real 1.5L", "kr"]),
  p("agua-cielo-sin-gas-625ml", "Agua Cielo Sin Gas", "Cielo", "Bebidas", "625 ml", 0.625, "L", ["Agua Cielo"]),
  p("agua-san-mateo-con-gas-500ml", "Agua San Mateo con Gas", "San Mateo", "Bebidas", "500 ml", 0.5, "L", ["Agua San Mateo"]),
  p("gatorade-500ml", "Gatorade", "Gatorade", "Bebidas", "500 ml", 0.5, "L", ["Gatorade 500ml"]),
  p("powerade-500ml", "Powerade", "Powerade", "Bebidas", "500 ml", 0.5, "L", ["Powerade 500ml"]),
  p("jugo-frugos-naranja-1l", "Jugo Frugos Naranja", "Frugos", "Bebidas", "1 L", 1, "L", ["Frugos Naranja"]),
  p("nectar-gloria-durazno-1l", "Néctar Gloria Durazno", "Gloria", "Bebidas", "1 L", 1, "L", ["Néctar Gloria Durazno"]),
  p("cafe-nescafe-tradicion-170g", "Café Nescafé Tradición", "Nescafé", "Bebidas", "170 g", 0.17, "kg", ["Café Nescafé"]),
  p("chicha-morada-watts-1.25l", "Chicha Morada Watts", "Watts", "Bebidas", "Botella 1.25 L", 1.25, "L", ["Chicha Morada Watts botella"]),
  p("cerveza-pilsen-callao-620ml", "Cerveza Pilsen Callao", "Pilsen Callao", "Cervezas", "Botella 620 ml", 0.62, "L", ["Cerveza Pilsen Callao 620ml"]),
  p("pack-cerveza-cristal-355ml-x6", "Pack Cerveza Cristal", "Cristal", "Cervezas", "Pack 6 x 355 ml", 2.13, "L", ["Cerveza Cristal six pack"]),
  p("cerveza-cusquena-dorada-620ml", "Cerveza Cusqueña Dorada", "Cusqueña", "Cervezas", "Botella 620 ml", 0.62, "L", ["Cerveza Cusqueña Dorada 620ml"]),
  p("pack-cerveza-corona-355ml-x6", "Pack Cerveza Corona", "Corona", "Cervezas", "Pack 6 x 355 ml", 2.13, "L", ["Cerveza Corona six pack"]),
  p("pack-cerveza-heineken-355ml-x6", "Pack Cerveza Heineken", "Heineken", "Cervezas", "Pack 6 x 355 ml", 2.13, "L", ["Cerveza Heineken six pack"]),
  p("cerveza-cusquena-trigo-620ml", "Cerveza Cusqueña Trigo", "Cusqueña", "Cervezas", "Botella 620 ml", 0.62, "L", ["Cerveza Cusqueña Trigo 620ml"]),
  p("cerveza-cusquena-negra-620ml", "Cerveza Cusqueña Negra", "Cusqueña", "Cervezas", "Botella 620 ml", 0.62, "L", ["Cerveza Cusqueña Negra"]),
  p("cerveza-stella-artois-355ml", "Cerveza Stella Artois", "Stella Artois", "Cervezas", "Botella 355 ml", 0.355, "L", ["Cerveza Stella Artois"]),
  p("cerveza-barena-620ml", "Cerveza Barena", "Barena", "Cervezas", "Botella 620 ml", 0.62, "L", ["Cerveza Barena"]),
  p("pack-cerveza-pilsen-355ml-x6", "Pack Cerveza Pilsen Callao", "Pilsen Callao", "Cervezas", "Pack 6 x 355 ml", 2.13, "L", ["Cerveza Pilsen six pack"]),
  p("pisco-quebranta-ocucaje-700ml", "Pisco Quebranta Ocucaje", "Ocucaje", "Licores", "700 ml", 0.7, "L", ["Pisco Ocucaje Quebranta"]),
  p("ron-cartavio-anejo-750ml", "Ron Cartavio Añejo", "Cartavio", "Licores", "750 ml", 0.75, "L", ["Ron Cartavio Añejo"]),
  p("whisky-johnnie-walker-red-750ml", "Whisky Johnnie Walker Red Label", "Johnnie Walker", "Licores", "750 ml", 0.75, "L", ["Whisky Johnnie Walker Red Label"]),
  p("vino-tabernero-reserva-750ml", "Vino Tinto Tabernero Reserva", "Tabernero", "Licores", "750 ml", 0.75, "L", ["Vino Tabernero Reserva"]),
  p("vino-queirolo-blanco-750ml", "Vino Blanco Santiago Queirolo", "Santiago Queirolo", "Licores", "750 ml", 0.75, "L", ["Vino Santiago Queirolo Blanco"]),
  p("pisco-porton-700ml", "Pisco Portón", "Portón", "Licores", "700 ml", 0.7, "L", ["Pisco Portón"]),
  p("ron-flor-de-cana-750ml", "Ron Flor de Caña", "Flor de Caña", "Licores", "750 ml", 0.75, "L", ["Ron Flor de Caña"]),
  p("vino-tacama-blanco-750ml", "Vino Tacama Blanco", "Tacama", "Licores", "750 ml", 0.75, "L", ["Vino Tacama Blanco"]),
  p("vino-espumante-tabernero-750ml", "Vino Espumante Tabernero", "Tabernero", "Licores", "750 ml", 0.75, "L", ["Espumante Tabernero", "champagne"]),
  p("palta-fuerte-kg", "Palta Fuerte", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Palta Fuerte"]),
  p("platano-seda-kg", "Plátano de Seda", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Plátano de Seda"]),
  p("manzana-israel-kg", "Manzana Israel", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Manzana Israel"]),
  p("limon-kg", "Limón", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Limón"]),
  p("tomate-italiano-kg", "Tomate Italiano", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Tomate Italiano", "tomate"]),
  p("cebolla-roja-kg", "Cebolla Roja", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Cebolla Roja"]),
  p("papa-blanca-kg", "Papa Blanca", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Papa Blanca"]),
  p("naranja-jugo-kg", "Naranja de Jugo", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Naranja de Jugo", "naranja"]),
  p("zanahoria-kg", "Zanahoria", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Zanahoria"]),
  p("brocoli-kg", "Brócoli", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Brócoli"]),
  p("lechuga-americana-unidad", "Lechuga Americana", "Selección", "Frutas y Verduras", "Unidad", 1, "unidad", ["Lechuga Americana"]),
  p("pepino-kg", "Pepino", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Pepino"]),
  p("pina-kg", "Piña", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Piña"]),
  p("sandia-kg", "Sandía", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Sandía"]),
  p("mandarina-kg", "Mandarina", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Mandarina"]),
  p("fresa-kg", "Fresa", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Fresa", "frutilla"]),
  p("camote-kg", "Camote", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Camote"]),
  p("yuca-kg", "Yuca", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Yuca"]),
  p("choclo-kg", "Choclo", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Choclo"]),
  p("aji-amarillo-kg", "Ají Amarillo", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Ají Amarillo"]),
  p("ajo-kg", "Ajo", "Selección", "Frutas y Verduras", "Por Kg", 1, "kg", ["Ajo"]),
  p("pollo-entero-san-fernando-kg", "Pollo Entero San Fernando", "San Fernando", "Carnes y Pescados", "Por Kg", 1, "kg", ["Pollo Entero San Fernando"]),
  p("pechuga-pollo-san-fernando-kg", "Pechuga de Pollo San Fernando", "San Fernando", "Carnes y Pescados", "Por Kg", 1, "kg", ["Pechuga de Pollo San Fernando"]),
  p("trozos-pollo-redondos-san-fernando-kg", "Trozos de Pollo Redondos", "San Fernando", "Carnes y Pescados", "Por Kg", 1, "kg", ["Trozos de Pollo San Fernando"]),
  p("bistec-res-kg", "Bistec de Res", "San Fernando", "Carnes y Pescados", "Por Kg", 1, "kg", ["Bistec de Res"]),
  p("carne-molida-res-kg", "Carne Molida de Res", "San Fernando", "Carnes y Pescados", "Por Kg", 1, "kg", ["Carne Molida de Res"]),
  p("filete-perico-kg", "Filete de Perico", "Pesquero", "Carnes y Pescados", "Por Kg", 1, "kg", ["Filete de Perico"]),
  p("chuleta-cerdo-kg", "Chuleta de Cerdo", "San Fernando", "Carnes y Pescados", "Por Kg", 1, "kg", ["Chuleta de Cerdo"]),
  p("tocino-ahumado-200g", "Tocino Ahumado", "San Fernando", "Carnes y Pescados", "200 g", 0.2, "kg", ["Tocino Ahumado San Fernando"]),
  p("alitas-pollo-san-fernando-kg", "Alitas de Pollo San Fernando", "San Fernando", "Carnes y Pescados", "Por Kg", 1, "kg", ["Alitas de Pollo"]),
  p("higado-pollo-kg", "Hígado de Pollo", "San Fernando", "Carnes y Pescados", "Por Kg", 1, "kg", ["Hígado de Pollo"]),
  p("lomo-fino-res-kg", "Lomo Fino de Res", "San Fernando", "Carnes y Pescados", "Por Kg", 1, "kg", ["Lomo Fino de Res"]),
  p("asado-tira-kg", "Asado de Tira", "San Fernando", "Carnes y Pescados", "Por Kg", 1, "kg", ["Asado de Tira"]),
  p("filete-bonito-kg", "Filete de Bonito", "Pesquero", "Carnes y Pescados", "Por Kg", 1, "kg", ["Filete de Bonito", "pescado"]),
  p("pota-kg", "Pota", "Pesquero", "Carnes y Pescados", "Por Kg", 1, "kg", ["Pota"]),
  p("langostinos-kg", "Langostinos", "Pesquero", "Carnes y Pescados", "Por Kg", 1, "kg", ["Langostinos"]),
  p("chorizo-parrillero-kg", "Chorizo Parrillero", "San Fernando", "Carnes y Pescados", "Por Kg", 1, "kg", ["Chorizo Parrillero"]),
  p("hot-dog-san-fernando-400g", "Hot Dog San Fernando", "San Fernando", "Carnes y Pescados", "Paquete 400 g", 0.4, "kg", ["Salchicha Hot Dog San Fernando"]),
  p("avena-quaker-tradicional-400g", "Avena Quaker Tradicional", "Quaker", "Saludable", "400 g", 0.4, "kg", ["Avena Quaker Tradicional"]),
  p("quinua-organica-500g", "Quinua Orgánica", "Sol de Andes", "Saludable", "500 g", 0.5, "kg", ["Quinua Orgánica 500g"]),
  p("leche-almendras-silk-1l", "Leche de Almendras Silk", "Silk", "Saludable", "1 L", 1, "L", ["Leche de Almendras Silk"]),
  p("barritas-cereal-quaker-x6", "Barritas de Cereal Quaker", "Quaker", "Saludable", "Pack 6 unid", 6, "unidad", ["Barritas de Cereal Quaker"]),
  p("mix-frutos-secos-200g", "Mix de Frutos Secos", "Nature's Heart", "Saludable", "200 g", 0.2, "kg", ["Mix Frutos Secos Nature's Heart"]),
  p("avena-tres-ositos-170g", "Avena Tres Ositos", "Tres Ositos", "Saludable", "170 g", 0.17, "kg", ["Avena Tres Ositos"]),
  p("granola-angel-300g", "Granola Angel", "Angel", "Saludable", "300 g", 0.3, "kg", ["Granola Angel"]),
  p("semillas-chia-natures-heart-100g", "Semillas de Chía", "Nature's Heart", "Saludable", "100 g", 0.1, "kg", ["Semillas de Chía"]),
  p("pasas-negras-natures-heart-100g", "Pasas Negras", "Nature's Heart", "Saludable", "100 g", 0.1, "kg", ["Pasas Negras"]),
  p("miel-abeja-natures-heart-375g", "Miel de Abeja", "Nature's Heart", "Saludable", "375 g", 0.375, "kg", ["Miel de Abeja"]),
  p("miel-abeja-bells-600g", "Miel de Abeja Bell's", "Bell's", "Saludable", "Frasco 600 g", 0.6, "kg", ["Miel de Abeja Bells frasco"]),
  p("miel-abeja-reyna-oxapampa-300g", "Miel de Abeja La Reyna de Oxapampa", "La Reyna de Oxapampa", "Saludable", "Frasco 300 g", 0.3, "kg", ["Miel de Abeja La Reyna de Oxapampa"]),
  p("miel-abeja-hacienda-najar-1kg", "Miel de Abeja Hacienda de Najar", "Hacienda de Najar", "Saludable", "Frasco 1 kg", 1, "kg", ["Miel de Abeja Hacienda de Najar"]),
  p("miel-abeja-amorely-500g", "Miel de Abeja Amorely", "Amorely", "Saludable", "500 g", 0.5, "kg", ["Miel de Abeja Amorely"]),
  p("leche-avena-silk-1l", "Leche de Avena Silk", "Silk", "Saludable", "1 L", 1, "L", ["Leche de Avena"]),
  p("barritas-proteina-quaker-x5", "Barritas Proteína Quaker", "Quaker", "Saludable", "Pack 5 unid", 5, "unidad", ["Barritas de Proteína"]),
  p("edulcorante-splenda-200tab", "Edulcorante Splenda", "Splenda", "Saludable", "200 tabletas", 200, "unidad", ["Edulcorante Splenda"]),
  p("pan-molde-bimbo-integral-650g", "Pan de Molde Bimbo Integral", "Bimbo", "Panadería", "650 g", 0.65, "kg", ["Pan de Molde Bimbo Integral"]),
  p("pan-frances-x10", "Pan Francés", "Panadería", "Panadería", "Pack x10", 10, "unidad", ["Pan Francés"]),
  p("croissant-mantequilla-x4", "Croissant Mantequilla", "Panadería", "Panadería", "Pack x4", 4, "unidad", ["Croissant Mantequilla"]),
  p("pan-pita-x6", "Pan Pita", "Panadería", "Panadería", "Pack x6", 6, "unidad", ["Pan Pita"]),
  p("keke-ingles-bimbo-400g", "Keke Inglés Bimbo", "Bimbo", "Panadería", "400 g", 0.4, "kg", ["Keke Inglés Bimbo"]),
  p("pan-hamburguesa-bimbo-x8", "Pan para Hamburguesa Bimbo", "Bimbo", "Panadería", "Pack x8", 8, "unidad", ["Pan Hamburguesa Bimbo"]),
  p("pan-hot-dog-bimbo-x8", "Pan para Hot Dog Bimbo", "Bimbo", "Panadería", "Pack x8", 8, "unidad", ["Pan Hot Dog Bimbo"]),
  p("tostadas-bimbo-integral-300g", "Tostadas Bimbo Integral", "Bimbo", "Panadería", "300 g", 0.3, "kg", ["Tostadas Bimbo"]),
  p("queque-tres-leches-porcion", "Queque Tres Leches", "Panadería", "Panadería", "Porción", 1, "unidad", ["Queque Tres Leches"]),
  p("alfajores-maicena-x6", "Alfajores de Maicena", "Panadería", "Panadería", "Pack x6", 6, "unidad", ["Alfajores de Maicena"]),
  p("pan-integral-artesanal-500g", "Pan Integral Artesanal", "Panadería", "Panadería", "500 g", 0.5, "kg", ["Pan Integral Artesanal"]),
  p("salsa-soya-kikkoman-150ml", "Salsa de Soya Kikkoman", "Kikkoman", "Market Asiático", "150 ml", 0.15, "L", ["Salsa de Soya Kikkoman"]),
  p("sillao-naruto-500ml", "Sillao Naruto", "Naruto", "Market Asiático", "500 ml", 0.5, "L", ["Sillao Naruto"]),
  p("fideos-chinos-saltado-250g", "Fideos Chinos para Saltado", "Yakisoba", "Market Asiático", "250 g", 0.25, "kg", ["Fideos Chinos para Saltado", "fideos tallarin saltado"]),
  p("arroz-jazmin-1kg", "Arroz Jazmín", "Genérico", "Market Asiático", "1 Kg", 1, "kg", ["Arroz Jazmín 1kg"]),
  p("salsa-ostion-255g", "Salsa de Ostión", "Lee Kum Kee", "Market Asiático", "255 g", 0.255, "kg", ["Salsa de Ostión Lee Kum Kee"]),
  p("sriracha-200ml", "Salsa Sriracha", "Huy Fong", "Market Asiático", "200 ml", 0.2, "L", ["Salsa Sriracha"]),
  p("kion-fresco-kg", "Kión Fresco", "Selección", "Market Asiático", "Por Kg", 1, "kg", ["Kión", "gengibre"]),
  p("aceite-ajonjoli-la-preferida-150ml", "Aceite de Ajonjolí", "La Preferida", "Market Asiático", "150 ml", 0.15, "L", ["Aceite de Ajonjolí"]),
  p("fideos-udon-250g", "Fideos Udon", "Genérico", "Market Asiático", "250 g", 0.25, "kg", ["Fideos Udon"]),
  p("pasta-miso-250g", "Pasta de Miso", "Genérico", "Market Asiático", "250 g", 0.25, "kg", ["Pasta de Miso"]),
  p("vinagre-arroz-300ml", "Vinagre de Arroz", "Genérico", "Market Asiático", "300 ml", 0.3, "L", ["Vinagre de Arroz"]),
  p("arroz-costeno-extra-750g", "Arroz Costeño Extra", "Costeño", "Abarrotes", "750 g", 0.75, "kg", ["Arroz Costeño Extra 750g"]),
  p("arroz-paisana-750g", "Arroz Paisana", "Paisana", "Abarrotes", "750 g", 0.75, "kg", ["Arroz Paisana 750g"]),
  p("huevos-rojos-san-fernando-x30", "Huevos Rojos San Fernando", "San Fernando", "Abarrotes", "Panal x30", 30, "unidad", ["Huevos Rojos San Fernando panal x30"]),
  p("huevos-blancos-x30", "Huevos Blancos", "Genérico", "Abarrotes", "Panal x30", 30, "unidad", ["Huevos Blancos panal x30"]),
  p("aceite-primor-1l", "Aceite Primor", "Primor", "Abarrotes", "1 L", 1, "L", ["Aceite Primor 1L"]),
  p("aceite-cocinero-1l", "Aceite Cocinero", "Cocinero", "Abarrotes", "1 L", 1, "L", ["Aceite Cocinero 1L"]),
  p("azucar-rubia-cartavio-1kg", "Azúcar Rubia Cartavio", "Cartavio", "Abarrotes", "1 Kg", 1, "kg", ["Azúcar Rubia Cartavio 1kg"]),
  p("fideos-don-vittorio-spaghetti-500g", "Fideos Don Vittorio Spaghetti", "Don Vittorio", "Abarrotes", "500 g", 0.5, "kg", ["Fideos Don Vittorio Spaghetti"]),
  p("arroz-nicolini-extra-750g", "Arroz Nicolini Extra", "Nicolini", "Abarrotes", "750 g", 0.75, "kg", ["Arroz Nicolini"]),
  p("arroz-costeno-superior-750g", "Arroz Costeño Superior", "Costeño", "Abarrotes", "750 g", 0.75, "kg", ["Arroz Costeño Superior"]),
  p("fideos-nicolini-tallarin-500g", "Fideos Nicolini Tallarín", "Nicolini", "Abarrotes", "500 g", 0.5, "kg", ["Fideos Nicolini"]),
  p("fideos-molitalia-canuto-500g", "Fideos Molitalia Canuto", "Molitalia", "Abarrotes", "500 g", 0.5, "kg", ["Fideos Molitalia Canuto"]),
  p("salsa-tomate-alacena-200g", "Salsa de Tomate Alacena", "Alacena", "Abarrotes", "200 g", 0.2, "kg", ["Salsa de Tomate"]),
  p("mayonesa-alacena-473g", "Mayonesa Alacena", "Alacena", "Abarrotes", "473 g", 0.473, "kg", ["Mayonesa Alacena"]),
  p("ketchup-alacena-397g", "Ketchup Alacena", "Alacena", "Abarrotes", "397 g", 0.397, "kg", ["Ketchup Alacena"]),
  p("mostaza-alacena-200g", "Mostaza Alacena", "Alacena", "Abarrotes", "200 g", 0.2, "kg", ["Mostaza Alacena"]),
  p("atun-florida-170g", "Atún Florida en Aceite", "Florida", "Abarrotes", "170 g", 0.17, "kg", ["Atún Florida"]),
  p("atun-gloria-170g", "Atún Gloria en Agua", "Gloria", "Abarrotes", "170 g", 0.17, "kg", ["Atún Gloria"]),
  p("leche-evaporada-ideal-400g", "Leche Evaporada Ideal", "Ideal", "Abarrotes", "400 g", 0.4, "kg", ["Leche Evaporada Ideal"]),
  p("sal-cocina-emsal-1kg", "Sal de Cocina Emsal", "Emsal", "Abarrotes", "1 Kg", 1, "kg", ["Sal Emsal"]),
  p("avena-quaker-hojuelas-620g", "Avena Quaker en Hojuelas", "Quaker", "Abarrotes", "620 g", 0.62, "kg", ["Avena en Hojuelas"]),
  p("galletas-soda-field-x6", "Galletas de Soda Field", "Field", "Abarrotes", "Pack x6", 6, "unidad", ["Galletas Soda Field"]),
  p("galletas-morochas-costa-x6", "Galletas Morochas", "Costa", "Abarrotes", "Pack x6", 6, "unidad", ["Galletas Morochas"]),
  p("chocolate-sublime-x6", "Chocolate Sublime", "Sublime", "Abarrotes", "Pack x6", 6, "unidad", ["Chocolate Sublime"]),
  p("cocoa-winters-500g", "Cocoa Winter's", "Winter's", "Abarrotes", "500 g", 0.5, "kg", ["Cocoa Winters"]),
  p("gelatina-negrita-x4", "Gelatina Negrita", "Negrita", "Abarrotes", "Pack x4", 4, "unidad", ["Gelatina Negrita"]),
  p("hielo-bolsa-2kg", "Hielo en Cubos", "Genérico", "Abarrotes", "Bolsa 2 kg", 2, "kg", ["Hielo en cubos bolsa 2kg"]),
  p("frijol-canario-nortenita-500g", "Frijol Canario Norteñita", "Norteñita", "Abarrotes", "Bolsa 500 g", 0.5, "kg", ["Frijol Canario Norteñita"]),
  p("lenteja-nortenita-500g", "Lenteja Norteñita", "Norteñita", "Abarrotes", "Bolsa 500 g", 0.5, "kg", ["Lenteja Norteñita"]),
  p("garbanzo-nortenita-500g", "Garbanzo Norteñita", "Norteñita", "Abarrotes", "Bolsa 500 g", 0.5, "kg", ["Garbanzo Norteñita"]),
  p("consome-pollo-maggi-x12", "Consomé de Pollo Maggi", "Maggi", "Abarrotes", "Caja 12 cubos", 12, "unidad", ["Consome de Pollo Maggi cubos"]),
  p("paracetamol-500mg-x10", "Paracetamol 500 mg", "Genérico", "Farmacia", "Caja x10", 10, "unidad", ["Paracetamol 500mg caja x10"]),
  p("alcohol-gel-purell-250ml", "Alcohol en Gel Purell", "Purell", "Farmacia", "250 ml", 0.25, "L", ["Alcohol en Gel Purell"]),
  p("curitas-nexcare-x20", "Curitas Nexcare", "Nexcare", "Farmacia", "Caja x20", 20, "unidad", ["Curitas Nexcare caja x20"]),
  p("protector-solar-nivea-fps50-200ml", "Protector Solar Nivea Sun FPS50", "Nivea", "Farmacia", "200 ml", 0.2, "L", ["Protector Solar Nivea FPS50"]),
  p("panales-huggies-talla-m-x30", "Pañales Huggies Talla M", "Huggies", "Farmacia", "Paquete x30", 30, "unidad", ["Pañales Huggies Talla M"]),
  p("toallas-kotex-x10", "Toallas Higiénicas Kotex", "Kotex", "Farmacia", "Paquete x10", 10, "unidad", ["Toallas Higiénicas Kotex"]),
  p("alcohol-medicinal-70-250ml", "Alcohol Medicinal 70°", "Genérico", "Farmacia", "250 ml", 0.25, "L", ["Alcohol Medicinal 70 grados"]),
  p("ibuprofeno-400mg-x10", "Ibuprofeno 400 mg", "Genérico", "Farmacia", "Caja x10", 10, "unidad", ["Ibuprofeno 400mg"]),
  p("panadol-500mg-x10", "Panadol 500 mg", "Panadol", "Farmacia", "Caja x10", 10, "unidad", ["Panadol"]),
  p("suero-oral-sobre", "Suero Oral", "Genérico", "Farmacia", "Sobre", 1, "unidad", ["Suero Oral"]),
  p("gasas-esteriles-x10", "Gasas Estériles", "Genérico", "Farmacia", "Pack x10", 10, "unidad", ["Gasas Estériles"]),
  p("shampoo-head-shoulders-375ml", "Shampoo Head & Shoulders", "Head & Shoulders", "Farmacia", "375 ml", 0.375, "L", ["Shampoo Head and Shoulders"]),
  p("jabon-dove-x3", "Jabón Dove", "Dove", "Farmacia", "Pack x3", 3, "unidad", ["Jabón Dove"]),
  p("pasta-dental-colgate-90g", "Pasta Dental Colgate", "Colgate", "Farmacia", "90 g", 0.09, "kg", ["Pasta Dental Colgate"]),
  p("desodorante-rexona-150ml", "Desodorante Rexona", "Rexona", "Farmacia", "150 ml", 0.15, "L", ["Desodorante Rexona"]),
  p("papel-elite-doble-hoja-x4", "Papel Higiénico Elite Doble Hoja", "Elite", "Cuidado del hogar", "Pack x4", 4, "unidad", ["Papel Higiénico Elite Doble Hoja x4"]),
  p("papel-elite-suave-x8", "Papel Higiénico Elite Suave", "Elite", "Cuidado del hogar", "Pack x8", 8, "unidad", ["Papel Higiénico Elite Suave x8"]),
  p("papel-noble-x4", "Papel Higiénico Noble", "Noble", "Cuidado del hogar", "Pack x4", 4, "unidad", ["Papel Higiénico Noble x4"]),
  p("detergente-ariel-1kg", "Detergente Ariel", "Ariel", "Cuidado del hogar", "1 Kg", 1, "kg", ["Detergente Ariel"]),
  p("detergente-bolivar-900g", "Detergente Bolívar", "Bolívar", "Cuidado del hogar", "900 g", 0.9, "kg", ["Detergente Bolívar"]),
  p("lavavajilla-sapolio-750ml", "Lavavajilla Sapolio", "Sapolio", "Cuidado del hogar", "750 ml", 0.75, "L", ["Lavavajilla Sapolio"]),
  p("lejia-sapolio-1l", "Lejía Sapolio", "Sapolio", "Cuidado del hogar", "1 L", 1, "L", ["Lejía Sapolio"]),
  p("suavizante-bolivar-900ml", "Suavizante Bolívar", "Bolívar", "Cuidado del hogar", "900 ml", 0.9, "L", ["Suavizante Bolívar"]),
  p("limpiador-multiuso-sapolio-900ml", "Limpiador Multiuso Sapolio", "Sapolio", "Cuidado del hogar", "900 ml", 0.9, "L", ["Limpiador Multiuso"]),
  p("bolsas-basura-sanitas-x10", "Bolsas de Basura Sanitas", "Sanitas", "Cuidado del hogar", "Pack x10", 10, "unidad", ["Bolsas de Basura"]),
  p("papel-toalla-scott-x2", "Papel Toalla Scott", "Scott", "Cuidado del hogar", "Pack x2", 2, "unidad", ["Papel Toalla Scott"]),
  p("servilletas-elite-x100", "Servilletas Elite", "Elite", "Cuidado del hogar", "Pack x100", 100, "unidad", ["Servilletas Elite"]),
  p("ambientador-glade-360ml", "Ambientador Glade", "Glade", "Cuidado del hogar", "360 ml", 0.36, "L", ["Ambientador Glade"]),
  p("insecticida-baygon-360ml", "Insecticida Baygon", "Baygon", "Cuidado del hogar", "Spray 360 ml", 0.36, "L", ["Insecticida Baygon spray"]),
  p("pilas-duracell-aa-x4", "Pilas Duracell AA", "Duracell", "Cuidado del hogar", "Pack x4", 4, "unidad", ["Pilas Duracell AA"]),
  p("aceite-oliva-borges-500ml", "Aceite de Oliva Extra Virgen Borges", "Borges", "Premium y Gourmet", "500 ml", 0.5, "L", ["Aceite de Oliva Borges Extra Virgen"]),
  p("queso-parmesano-reggianito-200g", "Queso Parmesano Reggianito", "Importado", "Premium y Gourmet", "200 g", 0.2, "kg", ["Queso Parmesano Reggianito"]),
  p("jamon-serrano-importado-100g", "Jamón Serrano Importado", "Importado", "Premium y Gourmet", "100 g", 0.1, "kg", ["Jamón Serrano"]),
  p("chocolate-lindt-100g", "Chocolate Lindt Excellence 70%", "Lindt", "Premium y Gourmet", "100 g", 0.1, "kg", ["Chocolate Lindt Excellence"]),
  p("cafe-altomayo-grano-250g", "Café Gourmet en Grano Altomayo", "Altomayo", "Premium y Gourmet", "250 g", 0.25, "kg", ["Café Altomayo en grano"]),
  p("salmon-ahumado-noruego-150g", "Salmón Ahumado Noruego", "Importado", "Premium y Gourmet", "150 g", 0.15, "kg", ["Salmón Ahumado"]),
  p("mermelada-gourmet-fresa-280g", "Mermelada Gourmet de Fresa", "Wong Selección", "Premium y Gourmet", "280 g", 0.28, "kg", ["Mermelada Gourmet"]),
  p("pasta-barilla-500g", "Pasta Barilla", "Barilla", "Premium y Gourmet", "500 g", 0.5, "kg", ["Pasta Barilla"]),
  p("aceite-oliva-carbonell-500ml", "Aceite de Oliva Carbonell", "Carbonell", "Premium y Gourmet", "500 ml", 0.5, "L", ["Aceite Oliva Carbonell"]),
  p("te-gourmet-hierbaluisa-25", "Té Gourmet Hierba Luisa", "McCollins", "Premium y Gourmet", "Caja x25", 25, "unidad", ["Té Hierba Luisa"]),
  p("galletas-danesas-mantequilla-400g", "Galletas Danesas de Mantequilla", "Royal Dansk", "Premium y Gourmet", "400 g", 0.4, "kg", ["Galletas Danesas"]),
  p("chocolate-ferrero-rocher-x8", "Chocolate Ferrero Rocher", "Ferrero", "Premium y Gourmet", "Caja x8", 8, "unidad", ["Ferrero Rocher"]),
];

function p(id, name, brand, category, presentation, qty, unit, extraSearchTerms) {
  return {
    id,
    name,
    brand,
    category,
    presentation,
    qty,
    unit,
    ean: null,
    searchTerms: [name, ...(extraSearchTerms || [])],
  };
}
